/**
 * `gateway init` — scaffold a .env file with auto-generated secrets.
 */

import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { randomBytes } from 'node:crypto';
import { ok, fail } from '../shared.js';

function randomHex(bytes: number): string {
  return randomBytes(bytes).toString('hex');
}

function randomAlphaNum(length: number): string {
  const chars = 'ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789';
  let out = '';
  const rand = randomBytes(length * 2);
  for (let i = 0; i < length; i++) {
    out += chars[rand[i] % chars.length];
  }
  return out;
}

export interface InitOptions {
  force?: boolean;
}

export async function runInit(options: InitOptions): Promise<void> {
  const envPath = resolve(process.cwd(), '.env');

  if (existsSync(envPath) && !options.force) {
    fail(`.env already exists. Use --force to overwrite.`);
    process.exit(1);
  }

  const jwtSecret = randomHex(32);             // 64-char hex
  const encryptionKey = randomHex(32);         // 64-char hex
  const adminPassword = randomAlphaNum(16);    // readable alphanum

  const content = [
    '# Simplaix Gateway — generated by `gateway init`',
    '# Edit values as needed, then run: gateway start',
    '',
    '# Database: SQLite file (default, zero setup)',
    '# Switch to PostgreSQL: DATABASE_URL=postgres://user:pass@host/db',
    `DATABASE_URL=file:./gateway.db`,
    '',
    `PORT=7521`,
    '',
    '# JWT secret — keep this private',
    `JWT_SECRET=${jwtSecret}`,
    '',
    '# Encryption key for stored credentials (32 random bytes as hex)',
    `CREDENTIAL_ENCRYPTION_KEY=${encryptionKey}`,
    '',
    '# Initial admin account created on first `gateway start`',
    `ADMIN_EMAIL=admin@example.com`,
    `ADMIN_PASSWORD=${adminPassword}`,
    '',
  ].join('\n');

  writeFileSync(envPath, content, 'utf8');

  ok('.env created');
  console.log('');
  console.log('  Admin credentials:');
  console.log(`    Email:    admin@example.com`);
  console.log(`    Password: ${adminPassword}`);
  console.log('');
  console.log('  Next steps:');
  console.log('    gateway start           # start the server');
  console.log('    gateway status          # verify connection');
  console.log(
    '    gateway admin create    # create additional admin users',
  );
}
